---
title: "Homework_Week_6"
author: "Arora"
date: "October 23, 2017"
output: html_document
---
```{r, eval=FALSE}
Z.prop.test <- function(p1, n1, p0, p2, n2, alternative = "two.tailed", conf.level = 0.975, k=10) 
    p<-rep(NA, k)
    for (i in 1:k){
      p1
      n1<-n
      p0
      conf.level<-0.975
      p2<-NULL
      n2<-NULL
      alpha=0.05
      Z <- p2-p1/(sqrt((p0)*(1-p0)*((1/n1)+(1/n2))))
      alternative<-"two tailed"

    if (alternative == "less") {
            P<-p[i] <- pnorm(z, lower.tail = TRUE)  # calculates the associated p value
            hyp <- "p1 < p0"
        }
        if (alternative == "greater") {
            P<-p[i] <- pnorm(z, lower.tail = FALSE)
            hyp <- "p1 > p0"
        }
        if (alternative == "two.tailed") {
            if (z > 0) {
                P<-p[i] <- 2 * pnorm(z, lower.tail = FALSE)
            }
            if (z < 0) {
                P<-p[i] <- 2 * pnorm(z, lower.tail = TRUE)
            }
      
    if (p2 == is.NULL) {
      Z=(p1-p0)/sqrt((p0*(1-p0))/n1)
    }
     if (alternative == "less") {
            P<-p[i] <- pnorm(z, lower.tail = TRUE)  # calculates the associated p value
            hyp <- "p1 < p0"
        }
        if (alternative == "greater") {
            P<-p[i] <- pnorm(z, lower.tail = FALSE)
            hyp <- "p1 > p0"
        }
        if (alternative == "two.tailed") {
            if (z > 0) {
                P<-p[i] <- 2 * pnorm(z, lower.tail = FALSE)
            }
            if (z < 0) {
                P<-p[i] <- 2 * pnorm(z, lower.tail = TRUE)
            }
      
    if (n2 == is.NULL) {
     Z=(p1-p0)/sqrt((p0*(1-p0))/n1) 
    }
     if (alternative == "less") {
            P<-p[i] <- pnorm(z, lower.tail = TRUE)  # calculates the associated p value
            hyp <- "p1 < p0"
        }
        if (alternative == "greater") {
            P<-p[i] <- pnorm(z, lower.tail = FALSE)
            hyp <- "p1 > p0"
        }
        if (alternative == "two.tailed") {
            if (z > 0) {
                P<-p[i] <- 2 * pnorm(z, lower.tail = FALSE)
            }
            if (z < 0) {
                P<-p[i] <- 2 * pnorm(z, lower.tail = TRUE)
            }
      }
    }
  }

      alpha=0.05
      critical.value<-qnorm(1-alpha/2)
      p1.CI<-((p1*(1-p1))/n1)
      p2.CI<-((p2*(1-p2))/n2)
      SE=sqrt(p1.CI+p2.CI)
      addition<-(p1+p2)+(critical.value*SE)
      addition
      subtraction<-(p1+p2)-(critical.value*SE)
      subtraction
      CI<-c(subtraction, addition)
  

      #p is the probability of the sucess where s=1 and failure = 0
    p<-p1 #isn't that what the probability proportion is?
    n1 #this is the number of trials run
    if(n1*p1<5) {
        "Warning: the input does not allow for normality to be assumed"
    }
    if(n1*(1*p1)<5) {"Warning: the input does not allow for normality to be assumed"
    ##I didn't know which n and p where referred in this particular part of the homework so I used n1 and p1 because that seemed most logical
    }

return(Z)
return(CI)
return(P)
}
```




```{r}
library(curl)
f <- curl("https://github.com/fuzzyatelin/fuzzyatelin.github.io/blob/master/AN597_Fall17/KamilarAndCooperData.csv")
d <- read.csv(f, header = TRUE, sep = ",", stringsAsFactors = FALSE)
head(d)
```
